services:
  - type: web
    name: my-fastapi-app
    env: python-3.12.4
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    plan: free
