services:
  - type: web #web service
    name: chatroom-fksh #name of the service
    env: python-3.12.4
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0
    plan: free